### ISSUE TITLE
latte模型的pos_embed没有被正确初始化

### ISSUE THREAD

**Issue by weyeeji** [xdit-project/xDiT#255]
在运行latte模型时，出现如下报错，检查 pos_embed的确没有被正确初始化，返回为none
 Traceback (most recent call last):
   File "/xDiT/./examples/latte_example.py", line 78, in <module>
     main()
   File "/xDiT/./examples/latte_example.py", line 39, in main
     output = pipe(
   File "/miniconda3/envs/xdit/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
     return func(*args, **kwargs)
   File "/xDiT/xfuser/model_executor/pipelines/base_pipeline.py", line 133, in data_parallel_fn
     return func(self, *args, **kwargs)
   File "/xDiT/xfuser/model_executor/pipelines/base_pipeline.py", line 149, in check_naive_forward_fn
     return func(self, *args, **kwargs)
   File "/xDiT/xfuser/model_executor/pipelines/pipeline_latte.py", line 298, in __call__
     noise_pred = self.transformer(
   File "/miniconda3/envs/xdit/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
     return self._call_impl(*args, **kwargs)
   File "/miniconda3/envs/xdit/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
     return forward_call(*args, **kwargs)
   File "/xDiT/xfuser/model_executor/models/transformers/latte_transformer_3d.py", line 111, in forward
     hidden_states = self.pos_embed(
 TypeError: 'NoneType' object is not callable

**Comment by dannyxiaocn** [comment]
我没太遇到这个问题，你试着回退一下diffusers版本看一下？

**Comment by feifeibear** [comment]
我们可能需要用最新的diffusers版本去测试一下latte。
diffusers变化很快，可能会影响latte实现？
